notifications:
  slack: rest4hub:McnBEaeCAmAjAQZwGUMxOlSi

sudo: required

services:
  - docker

before_install:
  - make build release -e BRANCH=$TRAVIS_BRANCH
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  
script:
  - make publish -e BRANCH=$TRAVIS_BRANCH
